### ISSUE TITLE
Error Message: Incorrect Request. [Field 'launchId' shouldn't be null.] 

### ISSUE THREAD

**Issue by patel-5788** [reportportal/agent-readyapi#1]
Hi 
I have installed ReadyAPI plugin. and it was working fine till ReadyAPI version 2.2.0.
Recently we have updated to ReadyAPI 2.3.0. after that we are facing this issue.
Setup:  
 -ReadyAPI plugin Installed
 -Custom properties define
 ```
            
                    rp.username =arvind.patel
                    rp.uuid = ***********
                   rp.endpoint = https://rpserverurl.com
                  rp.launch = Rest-Services
                  rp.project = Regression
                  rp.tags = regression;qa
```
-Reloaded project

While running i am getting below stacktrace from log 
```
Error during starting test case:
Report Portal returned error
Status code: 400
Status message: Bad Request
Error Message: Incorrect Request. [Field 'launchId' shouldn't be null.] 
Error Type: INCORRECT_REQUEST
Stack Trace: 
com.epam.reportportal.exception.ReportPortalClientException: Report Portal returned error
Status code: 400
Status message: Bad Request
Error Message: Incorrect Request. [Field 'launchId' shouldn't be null.] 
Error Type: INCORRECT_REQUEST
Stack Trace: 
	at com.epam.reportportal.service.ReportPortalErrorHandler.handleClientError(ReportPortalErrorHandler.java:47)
	at com.epam.reportportal.restclient.endpoint.DefaultErrorHandler.handle(DefaultErrorHandler.java:73)
	at com.epam.reportportal.restclient.endpoint.DefaultErrorHandler.handle(DefaultErrorHandler.java:40)
	at com.epam.reportportal.restclient.endpoint.HttpClientRestEndpoint.executeInternal(HttpClientRestEndpoint.java:341)
	at com.epam.reportportal.restclient.endpoint.HttpClientRestEndpoint.post(HttpClientRestEndpoint.java:106)
	at com.epam.reportportal.service.ReportPortalService.startTestItem(ReportPortalService.java:246)
	at com.epam.reportportal.soapui.service.SoapUIServiceImpl.startTestCase(SoapUIServiceImpl.java:184)
	at com.epam.reportportal.soapui.listeners.RPTestSuiteRunListener.beforeTestCase(RPTestSuiteRunListener.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.eviware.soapui.plugins.PluginProxies$DelegatingHandler.invoke(PluginProxies.java:116)
	at com.sun.proxy.$Proxy47.beforeTestCase(Unknown Source)
	at com.eviware.soapui.impl.wsdl.testcase.WsdlTestSuiteRunner$4.notifyListener(WsdlTestSuiteRunner.java:258)
	at com.eviware.soapui.impl.wsdl.testcase.WsdlTestSuiteRunner.notifyListeners(WsdlTestSuiteRunner.java:286)
	at com.eviware.soapui.impl.wsdl.testcase.WsdlTestSuiteRunner.notifyBeforeRunTestCase(WsdlTestSuiteRunner.java:255)
	at com.eviware.soapui.impl.wsdl.testcase.WsdlTestSuiteRunner.runSequential(WsdlTestSuiteRunner.java:171)
	at com.eviware.soapui.impl.wsdl.testcase.WsdlTestSuiteRunner.internalRun(WsdlTestSuiteRunner.java:119)
	at com.eviware.soapui.impl.wsdl.testcase.WsdlTestSuiteRunner.internalRun(WsdlTestSuiteRunner.java:1)
	at com.eviware.soapui.impl.wsdl.support.AbstractTestRunner.run(AbstractTestRunner.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by patel-5788** [comment]
Hi @avarabyeu 
We did further analysis on this issue.
We inspect the rest call via fiddler and below are the details.

Setup Details:
ReadyAPI-agent plugin : 0.1
ReadyAPI version: 2.3.0

```
curl -X POST \
  http://***myserver***/api/v1/forge-schema/item/59eee11f36d1a000012d4f30 \
  -H 'Authorization: *******' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 0dd4fea2-2f40-3bff-d376-6bbc018efa91' \
  -d '
{"name":"create-extension","description":"REST_REQUEST","start_time":1521544600646,"type":"STEP"}

'
```
As per our understanding it looks like RP ReadyAPI plugin error. Please let me know if any further details require.

**Comment by avarabyeu** [comment]
project has been moved to [soapUI](https://github.com/reportportal/agent-java-soapui) and fixed there.
